// src/types/staffTypes.js

export const ROLES = {
    ADMIN: 'admin',
    PHARMACIST: 'pharmacist',
    ASSISTANT: 'assistant',
    CASHIER: 'cashier',
    INVENTORY_MANAGER: 'inventory_manager'
  };
  
  export const PERMISSIONS = {
    MANAGE_STAFF: 'manage_staff',
    MANAGE_INVENTORY: 'manage_inventory',
    MANAGE_PRESCRIPTIONS: 'manage_prescriptions',
    DISPENSE_MEDICINES: 'dispense_medicines',
    VIEW_REPORTS: 'view_reports',
    MANAGE_ROLES: 'manage_roles',
    HANDLE_PAYMENTS: 'handle_payments',
    VIEW_LOGS: 'view_logs'
  };
  
  export const ROLE_PERMISSIONS = {
    [ROLES.ADMIN]: [
      PERMISSIONS.MANAGE_STAFF,
      PERMISSIONS.MANAGE_INVENTORY,
      PERMISSIONS.MANAGE_PRESCRIPTIONS,
      PERMISSIONS.DISPENSE_MEDICINES,
      PERMISSIONS.VIEW_REPORTS,
      PERMISSIONS.MANAGE_ROLES,
      PERMISSIONS.HANDLE_PAYMENTS,
      PERMISSIONS.VIEW_LOGS
    ],
    [ROLES.PHARMACIST]: [
      PERMISSIONS.MANAGE_INVENTORY,
      PERMISSIONS.MANAGE_PRESCRIPTIONS,
      PERMISSIONS.DISPENSE_MEDICINES,
      PERMISSIONS.VIEW_REPORTS,
      PERMISSIONS.HANDLE_PAYMENTS
    ],
    [ROLES.ASSISTANT]: [
      PERMISSIONS.MANAGE_PRESCRIPTIONS,
      PERMISSIONS.DISPENSE_MEDICINES,
      PERMISSIONS.HANDLE_PAYMENTS
    ],
    [ROLES.CASHIER]: [
      PERMISSIONS.HANDLE_PAYMENTS,
      PERMISSIONS.VIEW_REPORTS
    ],
    [ROLES.INVENTORY_MANAGER]: [
      PERMISSIONS.MANAGE_INVENTORY,
      PERMISSIONS.VIEW_REPORTS
    ]
  };